apiVersion: v1
kind: Pod
metadata:
  name: bookstorepod
  labels:
    app: backend
spec:
  containers:
    - name: bookstore-image
      image: srimayank1994/bookstore:v2
      imagePullPolicy: Always
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: regcred
